### ISSUE TITLE
Incorrect translation with French letters or characters

### ISSUE THREAD

**Issue by retkowsky** [IBMPredictiveAnalytics/Watson-Translate#1]
When I use the Watson Translate node with SPSS Modeler on French written sentences, I have some incorrect translation when some accentuated letters  or characters are present. Maybe there is something wrong with UTF? 
As you can see below lines 1 and 2 are correctly translated from English into French.
Lines 3 and 4 that contains some French accentuated characters are in this case not translated correctly.

![picture1](https://cloud.githubusercontent.com/assets/15341671/10756544/12467b28-7ca5-11e5-8cb2-1865e6524c44.jpg)

**Comment by gfilla** [comment]
Hi,

I tried to recreate this issue on version 16 and 17 but was unsucessful.  Can you provide more details like: 
- Version of Modeler
- Console output in translate node
- A document with a sample of your text.  I manually entered the phrases that were causing issues for you for the example below

![image](https://cloud.githubusercontent.com/assets/6307720/10801848/76e919c2-7d87-11e5-94d7-2626b08795a9.png)

**Comment by Wenpei** [comment]
close this since no feed back.
